import os

USE_LOCAL=False

ELASTIC_CO_USERNAME="elastic"
ELASTIC_CO_PASSWORD="JD7GKQytYEpoLrr2sPYav84V"
ELASTICSEARCH_PORT=9243
ELASTIC_HOST_KEY=f"https://{ELASTIC_CO_USERNAME}:{ELASTIC_CO_PASSWORD}@aa3dc9b9d95e4ab1b0b10c1e320eaed6.us-central1.gcp.cloud.es.io:{ELASTICSEARCH_PORT}"

if USE_LOCAL:
    ELASTICSEARCH_PORT = os.environ.get("ELASTICSEARCH_PORT", 9231)
    ELASTIC_HOST_KEY = f"http://localhost:{ELASTICSEARCH_PORT}" # django 500

ELASTICSEARCH_DSL = {
    'default': {
        'hosts': [ELASTIC_HOST_KEY]
    }
}